import { SessionProvider } from "next-auth/react"
import '@fontsource-variable/montserrat';
import "../../../app/globals.css";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SessionProvider>
      <body>
        {children}
      </body>
      </SessionProvider>
    </html>
  )
}
