/** Tokens de UI compartidos para componentes del blog (adaptados a CALETAS). */
export const stvn = {
  display: "font-special",
  badge: "chalk-badge",
  badgeCenter: "chalk-badge mx-auto flex w-fit max-w-full",
  section: "chalk-container py-14 sm:py-16 md:py-20",
  sectionMuted: "chalk-container border-t border-white/10 py-14 sm:py-16 md:py-20",
  card: "chalk-card",
  cardHover: "chalk-card transition-colors hover:border-white/20",
  reveal: "",
  revealCard: "",
  btnPrimary: "chalk-hero-btn chalk-hero-btn-primary",
  btnOutline: "chalk-hero-btn chalk-hero-btn-secondary",
  gradientText: "text-[var(--caleta-accent)]",
  h2: "font-special text-2xl font-bold tracking-tight text-white sm:text-3xl",
  h2Center: "font-special text-center text-2xl font-bold tracking-tight text-white sm:text-3xl md:text-4xl",
  headerShell: "",
  footerShell: "",
  navLink: "text-sm font-semibold text-white/75 hover:text-[var(--caleta-accent)]",
  navLinkActive: "text-sm font-semibold text-[var(--caleta-accent)]",
  authCard: "chalk-card rounded-2xl p-6 sm:p-8",
  input:
    "h-11 rounded-xl border border-white/15 bg-[#1C2D20] px-3 py-2.5 text-sm text-white placeholder:text-white/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#40C9A9]/40",
  linkMuted: "text-sm text-white/70 transition-colors hover:text-[var(--caleta-accent)]",
  sidebarNav: "flex items-center gap-3 rounded-xl px-3 py-2 text-sm font-medium transition-colors",
  sidebarNavActive: "bg-[#40C9A9]/15 text-white ring-1 ring-[#40C9A9]/30",
  sidebarNavInactive: "text-white/70 hover:bg-white/10 hover:text-white",
  statCard: "chalk-card p-6 sm:p-8",
  sectionLabel: "chalk-section-label mb-4",
  chatFab: "",
  chatUserBubble: "",
  chatAssistantBubble: "",
  chatChip: "",
} as const;
